openapi: 3.0.3
info:
  title: Product Ordering API
  description: Example TM Forum-style API used to demo SynaptDI compliance checking.
  version: 1.0.0
paths:
  /productOrder:
    get:
      summary: List product orders
      operationId: listProductOrder
      responses:
        '200':
          description: A list of product orders.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductOrder'
      parameters:
      - name: offset
        in: query
        description: Requested index for the start of resources to be provided.
        required: false
        schema:
          type: integer
      - name: limit
        in: query
        description: Requested number of resources to be provided in response.
        required: false
        schema:
          type: integer
      - name: fields
        in: query
        description: Comma-separated properties to be provided in response.
        required: false
        schema:
          type: string
      - name: sort
        in: query
        description: Comma-separated properties for sorting.
        required: false
        schema:
          type: string
    post:
      summary: Create a product order
      operationId: createProductOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductOrder'
      responses:
        '200':
          description: Created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductOrder'
        '201':
          description: Created
  /productOrder/{id}:
    get:
      summary: Retrieve a product order
      operationId: retrieveProductOrder
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: fields
        in: query
        description: Comma-separated properties to be provided in response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: A product order.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductOrder'
    delete:
      summary: Delete a product order
      operationId: deleteProductOrder
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Deleted.
        '204':
          description: No Content
components:
  schemas:
    ProductOrder:
      type: object
      properties:
        id:
          type: string
        ProductName:
          type: string
        OrderDate:
          type: string
          format: date-time
        orderStatus:
          type: string
        '@type':
          type: string
          description: When sub-classing, this defines the sub-class entity name.
    Error:
      type: object
      required:
      - code
      - reason
      properties:
        code:
          type: string
          description: Application-relevant detail, defined in the API or a common list.
        reason:
          type: string
          description: Explanation of the reason for the error which can be shown to a client user.
        message:
          type: string
          description: More details and corrective actions related to the error.
        status:
          type: string
          description: HTTP Error code extension.
        referenceError:
          type: string
          description: URI of documentation describing the error.
        '@type':
          type: string
          description: When sub-classing, this defines the sub-class entity name.
